ezpublish:
    siteaccess:
        default_siteaccess: eng
        list:
            - eng
            - admin
        groups:
            frontend_group:
                - eng
            admin_group:
                - admin
    system:
        frontend_group:
            translation_siteaccesses:
                - eng
            content:
                tree_root:
                    location_id: '%ngsite.default.locations.tree_root.id%'
        eng:
            design: app
            languages:
                - eng-GB
            session:
                name: eZSESSID
        admin:
            languages:
                - eng-GB
            session:
                name: eZSESSID
netgen_layouts:
    design_list:
        app:
            - app
    system:
        frontend_group:
            design: app
ezdesign:
    design_list:
        app:
            - app
            - common
            - standard
        admin:
            - admin
            - standard
            - common
