ibexa:
    repositories:
        default:
            fields_groups:
                list:
                    - content
                    - meta
                    - extras
                    - link1
                    - link2
                    - featured_item_1
                    - featured_item_2
                    - featured_item_3
                    - featured_item_4
                    - featured_item_5
                    - featured_item_6
                    - featured_item_7
                    - featured_item_8
                    - item_1
                    - item_2
                    - item_3
                    - item_4
                    - item_5
                    - item_6
                    - item_7
                    - item_8

    system:
        frontend_group:
            page_layout: "@ibexadesign/pagelayout.html.twig"
            user:
                login_template: "@ibexadesign/user/login.html.twig"
            field_templates:
                - { template: "@ibexadesign/content/parts/content_fields.html.twig", priority: 5000 }

netgen_tags:
    system:
        frontend_group:
            tag_view:
                template: "@ibexadesign/pages/tag.html.twig"
                related_content_list:
                    limit: 6
                    return_content_info: false
