nova_ezseo:
    system:
        default:
            default_metas:
                author: "Netgen"
                copyright: ~
                generator: "Ibexa DXP"
                MSSmartTagsPreventParsing: "TRUE"
            fieldtype_metas_identifier: "metas"
            fieldtype_metas:
                title:
                    label: 'Title'
                    default_pattern: "<title|name>"
                    required: true
                description:
                    label: 'Description'
                    default_pattern: "<description|short_description|title|name>"
                    minLength: 100
                    maxLength: 150
                keywords:
                    label: 'Keywords'
                    default_pattern: ~
            robots:
                sitemap:
                    - url: "https://%ngsite.fh_group.site_domain%/sitemap.xml"
            sitemap_excludes:
                contentTypeIdentifiers:
                    - file
                    - image
                    - ng_accordion_item
                    - ng_banner
                    - ng_component_about
                    - ng_component_features
                    - ng_component_hero
                    - ng_component_lead
                    - ng_component_logos
                    - ng_component_quote
                    - ng_container
                    - ng_cookie_policy
                    - ng_htmlbox
                    - ng_job_application_form
                    - ng_landing_page
                    - ng_lead_form
                    - ng_logo
                    - ng_menu_item
                    - ng_person
                    - ng_shortcut
                    - ng_site_info
                    - user
                    - user_group

