nova_ezseo:
    system:
        bold_group:
            default_metas:
                author: "Netgen"
                copyright: ~
                generator: "Ibexa DXP"
                MSSmartTagsPreventParsing: "TRUE"
            fieldtype_metas_identifier: "metadata"
            fieldtype_metas:
                title:
                    label: 'Title'
                    default_pattern: "<title|name>"
                    type: text
                description:
                    label: 'Description'
                    default_pattern: "<description|short_description|title|name>"
                    maxLength: 150
                    type: text
                keywords:
                    label: 'Keywords'
                    default_pattern: ~
                    type: text
            robots:
                sitemap:
                    - url: "https://%ngsite.bold_group.site_domain%/sitemap.xml"
            sitemap_includes:
                subtrees:
                    - "%ngsite.bold_group.locations.tree_root.id%"
                contentTypeIdentifiers:
                    - ng_article
                    - ng audio
                    - ng_blog_post
                    - ng_category
                    - ng_frontpage
                    - ng_gallery
                    - ng_job_position
                    - ng_news
        fh_group:
            default_metas:
                author: "Netgen"
                copyright: ~
                generator: "Ibexa DXP"
                MSSmartTagsPreventParsing: "TRUE"
            fieldtype_metas_identifier: "metadata"
            fieldtype_metas:
                title:
                    label: 'Title'
                    default_pattern: "<title|name>"
                    type: text
                description:
                    label: 'Description'
                    default_pattern: "<description|short_description|title|name>"
                    maxLength: 150
                    type: text
                keywords:
                    label: 'Keywords'
                    default_pattern: ~
                    type: text
            robots:
                sitemap:
                    - url: "https://%ngsite.fh_group.site_domain%/sitemap.xml"
            sitemap_includes:
                subtrees:
                    - "%ngsite.fh_group.locations.tree_root.id%"
                contentTypeIdentifiers:
                    - ng_article
                    - ng audio
                    - ng_blog_post
                    - ng_category
                    - ng_frontpage
                    - ng_gallery
                    - ng_job_position
                    - ng_news
