parameters:
    ngsite.default.template.user.activate: "@@ibexadesign/user/activate.html.twig"
    ngsite.default.template.user.activate_done: "@@ibexadesign/user/activate_done.html.twig"
    ngsite.default.template.user.activate_sent: "@@ibexadesign/user/activate_sent.html.twig"
    ngsite.default.template.user.activate_admin_activation_pending: "@@ibexadesign/user/activate_admin_activation_pending.html.twig"

    ngsite.default.template.user.forgot_password: "@@ibexadesign/user/forgot_password.html.twig"
    ngsite.default.template.user.forgot_password_sent: "@@ibexadesign/user/forgot_password_sent.html.twig"

    ngsite.default.template.user.register: "@@ibexadesign/user/register.html.twig"
    ngsite.default.template.user.register_success: "@@ibexadesign/user/register_success.html.twig"

    ngsite.default.template.user.reset_password: "@@ibexadesign/user/reset_password.html.twig"
    ngsite.default.template.user.reset_password_done: "@@ibexadesign/user/reset_password_done.html.twig"

    ngsite.default.template.user.mail.activate: "@@ibexadesign/user/mail/activate.html.twig"
    ngsite.default.template.user.mail.activate_already_active: "@@ibexadesign/user/mail/activate_already_active.html.twig"
    ngsite.default.template.user.mail.activate_disabled: "@@ibexadesign/user/mail/activate_disabled.html.twig"
    ngsite.default.template.user.mail.activate_not_registered: "@@ibexadesign/user/mail/activate_not_registered.html.twig"
    ngsite.default.template.user.mail.activate_admin_activation_pending: "@@ibexadesign/user/mail/activate_admin_activation_pending.html.twig"
    ngsite.default.template.user.mail.activate_admin_activation_required: "@@ibexadesign/user/mail/activate_admin_activation_required.html.twig"

    ngsite.default.template.user.mail.forgot_password: "@@ibexadesign/user/mail/forgot_password.html.twig"
    ngsite.default.template.user.mail.forgot_password_disabled: "@@ibexadesign/user/mail/forgot_password_disabled.html.twig"
    ngsite.default.template.user.mail.forgot_password_not_active: "@@ibexadesign/user/mail/forgot_password_not_active.html.twig"
    ngsite.default.template.user.mail.forgot_password_not_registered: "@@ibexadesign/user/mail/forgot_password_not_registered.html.twig"
    ngsite.default.template.user.mail.forgot_password_password_changed: "@@ibexadesign/user/mail/forgot_password_password_changed.html.twig"

    ngsite.default.template.user.mail.welcome: "@@ibexadesign/user/mail/welcome.html.twig"

    ngsite.default.template.errors.403: "@@ibexadesign/errors/403.html.twig"
    ngsite.default.template.errors.404: "@@ibexadesign/errors/404.html.twig"
    ngsite.default.template.errors.500: "@@ibexadesign/errors/500.html.twig"
    ngsite.default.template.errors.default: "@@ibexadesign/errors/default.html.twig"

    ngsite.default.template.search: "@@ibexadesign/search/search.html.twig"

    ngsite.default.template.menu: '@@ibexadesign/menu.html.twig'
