parameters:
    # Admin siteaccess group name
    admin_group_name: admin_group

    # This should be configured through semantic config, but this disables other
    # configuration forms: https://issues.ibexa.co/browse/IBX-7934
    ibexa.site_access.config.admin_group.user_preferences.additional_translations: ['de_DE']

    # Overriden to disable errors about missing "folder" content type (IBX-8285)
    ibexa.dam_widget.folder.content_type_identifier: ng_container

ibexa:
    siteaccess:
    system:
        admin_group:
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            # For admin this needs to contain all languages you want to translate content to on the given repository.
            #
            # languages list is disabled here to prevent merging with app configuration in
            # config/app/packages/ibexa_siteaccess.yaml and loosing languages order priority
            #
            # languages: [eng-GB]
            content_tree_module:
                contextual_tree_root_location_ids:
                    - 2 # Home (Content structure)
                    - 5 # Users
                    - 43 # Media
                    - 48 # Setup
            subtree_paths:
                content: /1/2/
                media: /1/43/
            assets:
                icon_sets:
                    default_icons: /bundles/ibexaadminui/img/ibexa-icons.svg
                default_icon_set: default_icons
            default_page: 'dashboard'
            content:
                default_ttl: 0
