when@dev:
    web_profiler:
        toolbar: true
        # By default disable showing of Admin UI "notifications/count" in web debug toolbar AJAX calls list to make it more manageable.
        excluded_ajax_paths: '(^/(app(_[\\w]+)?\\.php/)?_wdt)|/notifications/count'

    framework:
        profiler:
            collect_serializer_data: true
            # Optional: Skips generating profiles for subrequests by default due to dev performance
            only_main_requests: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
