system:
    frontend_group:
        view:
            item_view:
                default:
                    ibexa_content\gallery_thumb:
                        template: "@nglayouts/item/gallery_thumb/ibexa_content.html.twig"
                        match:
                            item\value_type: ibexa_content
                            item\view_type: gallery_thumb
                    ibexa_location\gallery_thumb:
                        template: "@nglayouts/item/gallery_thumb/ibexa_location.html.twig"
                        match:
                            item\value_type: ibexa_location
                            item\view_type: gallery_thumb
                ajax:
                    ibexa_content\gallery_thumb:
                        template: "@nglayouts/item/gallery_thumb/ibexa_content.html.twig"
                        match:
                            item\value_type: ibexa_content
                            item\view_type: gallery_thumb
                    ibexa_location\gallery_thumb:
                        template: "@nglayouts/item/gallery_thumb/ibexa_location.html.twig"
                        match:
                            item\value_type: ibexa_location
                            item\view_type: gallery_thumb

view:
    item_view:
        app:
            ibexa_content\siteapi\override:
                template: "nglayouts/app/item/ibexa_content.html.twig"
                match:
                    item\value_type: ibexa_content
            ibexa_location\siteapi\override:
                template: "nglayouts/app/item/ibexa_location.html.twig"
                match:
                    item\value_type: ibexa_location
