netgen_site_legacy:
    system:
        frontend_group:
            injected_merge_settings:
                site.ini:
                    SiteAccessRules/Rules:
                        - access;disable
                        - module;content/advancedsearch

        default:
            injected_merge_settings:
                site.ini:
                    ExtensionSettings/ActiveExtensions:
                        - app
                        - nglayouts
                        - ezplatformsearch
                        - ezrichtext
                        - ngadminui
                        - ngsymfonytools
                        - ngsite
                        - ngclasslist
                        - xrowmetadata
                        - birthday
                        - childrenindexer
                        - parentindexer
                        - hideuntildate
                        - ezclasslists
                        - ezchangeclass
                        - enhancedselection2
                        - ezmultiupload
                        - eztags
                        - ezjscore
                        - ezstarrating
                        - ezgmaplocation
                        - ezdemo
                        - ezoe

            injected_settings:
                content.ini:
                    ClassGroupIDs/Media: 2
                    ClassGroupIDs/Users: 3
                    # Setup class group was deleted long ago, this makes sure
                    # it doesn't mess up custom groups that have its' old ID
                    ClassGroupIDs/Setup: -1

                site.ini:
                    DatabaseSettings/Charset: "utf8mb4"
                    SiteSettings/DefaultAccess: "%ezpublish.siteaccess.default%"
                    SiteSettings/SiteList: "%ezpublish.siteaccess.list%"
                    SiteSettings/RootNodeDepth: 1
                    SiteSettings/SiteURL: "%ngsite.default.site_domain%"
                    SiteSettings/MetaDataArray: "%ngsite.default.site_settings.meta_data%"

                    SiteAccessSettings/AvailableSiteAccessList: "%ezpublish.siteaccess.list%"
                    SiteAccessSettings/RemoveSiteAccessIfDefaultAccess: enabled
                    # The following two parameters need to be "true" and "false" strings
                    # since eZ legacy config uses those, as opposed to booleans
                    SiteAccessSettings/ForceVirtualHost: "true"
                    SiteAccessSettings/CheckValidity: "false"

                    Session/SessionNameHandler: custom
                    UserSettings/LogoutRedirect: /

                    SiteAccessRules/Rules:
                        - access;disable
                        - module;user/register
                        - module;user/activate
                        - module;user/unactivated
                        - module;user/success
                        - module;user/forgotpassword
                        - module;ezinfo/about
                        - module;ezinfo/copyright
                        - module;content/tipafriend
                        - module;settings/edit
                        - module;layout
                        - module;visual
                        - module;shop

                    DesignSettings/DesignLocationCache: enabled

                    MailSettings/Transport: "%mailer_transport%"
                    MailSettings/TransportServer: "%mailer_host%"
                    MailSettings/TransportPort: "%mailer_port%"
                    MailSettings/TransportUser: "%mailer_user%"
                    MailSettings/TransportPassword: "%mailer_password%"
                    MailSettings/AdminEmail: "%ngsite.default.mail.sender_email%"
                    MailSettings/EmailSender: "%ngsite.default.mail.sender_email%"
