ngsite_view_modal:
    path: /view-modal/{contentId}
    defaults:
        _controller: 'App\Controller\ModalViewController::viewModal'

ngsite_info_collection_view_modal:
    path: /info-collection/view-modal/{formContentId}/{refererLocationId}
    defaults:
        _controller: 'App\Controller\InfoCollectionController:viewModal'
        refererLocationId: ~

ngsite_info_collection_ajax_submit:
    path: /info-collection/ajax-submit/{formContentId}
    methods: POST
    defaults:
        _controller: 'App\Controller\InfoCollectionController:ajaxSubmit'

